version: "3.9"

services:
  api:
    image: shunidex-api
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - api-net
  db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${HOME}/neo4j/data:/data
    networks:
      - api-net

networks:
  api-net: {}
